# Generated by Django 4.1.1 on 2023-12-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmodel',
            name='mcx_brk',
        ),
        migrations.RemoveField(
            model_name='adminmodel',
            name='mini_brk',
        ),
        migrations.RemoveField(
            model_name='adminmodel',
            name='nse_brk',
        ),
    ]
