# Generated by Django 4.1.1 on 2023-12-13 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MastrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.BooleanField(default=False)),
                ('master_limit', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Master Limit')),
                ('client_limit', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Client Limit')),
                ('add_order', models.BooleanField(blank=True, default=False, null=True, verbose_name='Add Order')),
                ('delete_trade', models.BooleanField(default=False, verbose_name='Delete Trade')),
                ('execute_pending_order', models.BooleanField(default=False, verbose_name='Execute Pending Order')),
                ('by_manual', models.BooleanField(default=False, verbose_name='By Manual')),
                ('trade_right', models.BooleanField(default=False, verbose_name='Trade Right')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='admin_app.adminmodel')),
                ('master_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_masters', to='master_app.mastrmodel')),
                ('master_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master Model',
                'verbose_name_plural': 'Master Model',
            },
        ),
    ]
