# Generated by Django 4.1.1 on 2023-12-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastrmodel',
            name='add_order',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Add Order'),
        ),
        migrations.AddField(
            model_name='mastrmodel',
            name='by_manual',
            field=models.BooleanField(default=False, verbose_name='By Manual'),
        ),
        migrations.AddField(
            model_name='mastrmodel',
            name='delete_trade',
            field=models.BooleanField(default=False, verbose_name='Delete Trade'),
        ),
        migrations.AddField(
            model_name='mastrmodel',
            name='execute_pending_order',
            field=models.BooleanField(default=False, verbose_name='Execute Pending Order'),
        ),
    ]
