# Generated by Django 4.1.1 on 2023-12-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCoinWithCaseModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('ex_change', models.CharField(max_length=200, verbose_name='ExChange')),
                ('identifier', models.CharField(max_length=200, verbose_name='Identifier')),
                ('breakup_qty', models.FloatField(default=0, verbose_name='Break Up Quantity')),
                ('max_qty', models.FloatField(default=0, verbose_name='Max Quantity')),
                ('breakup_lot', models.FloatField(default=0, verbose_name='Breakup Lot')),
                ('max_lot', models.FloatField(default=0, verbose_name='Max Lot')),
                ('lot_size', models.FloatField(default=0, verbose_name='Lot Size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeMarginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('exchange', models.CharField(blank=True, max_length=200, null=True, verbose_name='Exchange')),
                ('script', models.CharField(blank=True, max_length=200, null=True, verbose_name='script')),
                ('trade_margin', models.FloatField(default=0, verbose_name='Trade Margin')),
                ('disc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user_type', models.CharField(blank=True, choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Master', 'Master'), ('Client', 'Client')], max_length=20, null=True, verbose_name='User Type')),
                ('role', models.CharField(blank=True, choices=[('AREX', 'AREX'), ('DEMO', 'DEMO')], max_length=20, null=True, verbose_name='Role')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='User Name')),
                ('phone_number', models.CharField(default=0, max_length=10, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('credit', models.PositiveIntegerField(default=0, verbose_name='Credit')),
                ('balance', models.IntegerField(default=0, verbose_name='Balance')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remark')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Profile/%Y/%m/%d/', verbose_name='Avatar')),
                ('dob', models.DateField(blank=True, max_length=20, null=True, verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, default='', null=True, verbose_name='Address')),
                ('mcx', models.BooleanField(default=False, verbose_name='MCX')),
                ('sgx', models.BooleanField(default=False, verbose_name='SGX')),
                ('mini', models.BooleanField(default=False, verbose_name='MINI')),
                ('nse', models.BooleanField(default=False, verbose_name='NSE')),
                ('others', models.BooleanField(default=False, verbose_name='Others')),
                ('add_master', models.BooleanField(default=False, verbose_name='Add Master')),
                ('change_password', models.BooleanField(default=False, verbose_name='Change Password')),
                ('bet', models.BooleanField(default=False, verbose_name='Bet')),
                ('close_only', models.BooleanField(default=False, verbose_name='Close Only')),
                ('margin_sq', models.BooleanField(default=False, verbose_name='Margin Sq')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('auto_square_off', models.BooleanField(default=False, verbose_name='Auto Square off')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super User')),
                ('nse_brk', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NSE Brk')),
                ('mcx_brk', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='MCX Brk')),
                ('mini_brk', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='MINI Brk')),
            ],
            options={
                'verbose_name_plural': 'My User',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserCreditModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('opening', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('debit', models.FloatField(default=0)),
                ('closing', models.FloatField(default=0)),
                ('transection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transection', to=settings.AUTH_USER_MODEL)),
                ('user_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('trade_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketWatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('trade_coin_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Trade Coin Id')),
                ('market_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-trade_coin_id',),
            },
        ),
        migrations.CreateModel(
            name='LoginHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ip address')),
                ('method', models.CharField(blank=True, max_length=200, null=True, verbose_name='Method')),
                ('action', models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT')], max_length=20, null=True, verbose_name='action')),
                ('user_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Group')),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to='App.admincoinwithcasemodal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('symbol_name', models.CharField(blank=True, max_length=200, verbose_name='Symbol Name')),
                ('exchange', models.BooleanField(default=False, verbose_name='Exchange')),
                ('symbols', models.BooleanField(default=False, verbose_name='Symbols')),
                ('turnover', models.BooleanField(default=False, verbose_name='Turnover')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyAndSellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('trade_type', models.CharField(blank=True, choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT'), ('SL', 'SL')], max_length=20, null=True, verbose_name='Trade Type')),
                ('action', models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=20, null=True, verbose_name='Action')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('coin_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Coin Name')),
                ('ex_change', models.CharField(blank=True, max_length=200, null=True, verbose_name='Exchange')),
                ('is_pending', models.BooleanField(default=False, verbose_name='Is Pending')),
                ('identifer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Identifer')),
                ('ip_address', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Ip Address')),
                ('order_method', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Order Method')),
                ('trade_status', models.BooleanField(default=True, verbose_name='Trade Status')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='Is Cancel')),
                ('sl_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Sl Flag')),
                ('message', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Message')),
                ('stop_loss', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('buy_sell_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_sell_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='admincoinwithcasemodal',
            name='master_coins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_coins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountSummaryModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('particular', models.CharField(max_length=200, verbose_name='Particular')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('buy_sell_type', models.CharField(max_length=200, verbose_name='Buy Sell Type')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('average', models.FloatField(default=0, verbose_name='Average')),
                ('summary_flg', models.CharField(blank=True, choices=[('Profit/Loss', 'Profit/Loss'), ('Brokerage', 'Brokerage')], max_length=200, null=True, verbose_name='Type')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('closing', models.IntegerField(default=0, verbose_name='closing')),
                ('open_qty', models.IntegerField(default=0, verbose_name='Opening')),
                ('user_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
