# Generated by Django 4.1.1 on 2023-12-15 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mcx_brk',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='MCX Brk'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='mini_brk',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='MINI Brk'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='nse_brk',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NSE Brk'),
        ),
        migrations.CreateModel(
            name='LoginHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ip address')),
                ('method', models.CharField(blank=True, max_length=200, null=True, verbose_name='Method')),
                ('user_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
