# Generated by Django 4.1.1 on 2023-12-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupSettingsModel',
        ),
    ]
