# Generated by Django 4.1.1 on 2023-12-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyandsellmodel',
            name='message',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='buyandsellmodel',
            name='sl_flag',
            field=models.BooleanField(default=False, verbose_name='Sl Flag'),
        ),
    ]
