# Generated by Django 4.1.1 on 2023-12-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_delete_groupsettingsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Group')),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to='App.admincoinwithcasemodal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
