# Generated by Django 4.1.1 on 2023-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_buyandsellmodel_message_buyandsellmodel_sl_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyandsellmodel',
            name='is_cancel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Trade Status'),
        ),
        migrations.AlterField(
            model_name='buyandsellmodel',
            name='sl_flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sl Flag'),
        ),
    ]
