# Generated by Django 4.1.1 on 2023-12-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_admincoinwithcasemodal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminCoinWithCaseModal',
        ),
    ]
