# Generated by Django 4.1.1 on 2023-12-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_myuser_mcx_brk_myuser_mini_brk_myuser_nse_brk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistorymodel',
            name='action',
            field=models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT')], max_length=20, null=True, verbose_name='action'),
        ),
    ]
