# Generated by Django 4.1.1 on 2023-12-19 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_loginhistorymodel_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSummaryModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('particular', models.CharField(max_length=200, verbose_name='Particular')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('buy_sell_type', models.CharField(max_length=200, verbose_name='Buy Sell Type')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('average', models.IntegerField(default=0, verbose_name='Average')),
                ('type', models.CharField(blank=True, choices=[('Profit/Loss', 'Profit/Loss'), ('Brokerage', 'Brokerage')], max_length=200, null=True, verbose_name='Type')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('closing', models.IntegerField(default=0, verbose_name='closing')),
                ('opening', models.IntegerField(default=0, verbose_name='Opening')),
                ('user_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
