# Generated by Django 4.1.1 on 2023-12-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_groupsettingsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsettingsmodel',
            name='group_user',
        ),
        migrations.DeleteModel(
            name='AdminCoinWithCaseModal',
        ),
        migrations.DeleteModel(
            name='GroupSettingsModel',
        ),
    ]
