# Generated by Django 4.1.1 on 2023-12-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_accountsummarymodal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'My User'},
        ),
        migrations.RenameField(
            model_name='accountsummarymodal',
            old_name='opening',
            new_name='open_qty',
        ),
        migrations.RenameField(
            model_name='accountsummarymodal',
            old_name='type',
            new_name='summary_flg',
        ),
    ]
