# Generated by Django 4.1.1 on 2023-12-27 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_groupsettingsmodel_group_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminCoinWithCaseModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('ex_change', models.CharField(max_length=200, verbose_name='ExChange')),
                ('identifier', models.CharField(max_length=200, verbose_name='Identifier')),
                ('breakup_qty', models.FloatField(default=0, verbose_name='Break Up Quantity')),
                ('max_qty', models.FloatField(default=0, verbose_name='Max Quantity')),
                ('breakup_lot', models.FloatField(default=0, verbose_name='Breakup Lot')),
                ('max_lot', models.FloatField(default=0, verbose_name='Max Lot')),
                ('lot_size', models.FloatField(default=0, verbose_name='Lot Size')),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to='App.groupsettingsmodel')),
                ('master_coins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_coins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
