# Generated by Django 4.1.1 on 2023-12-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_groupsettingsmodel_admincoinwithcasemodal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincoinwithcasemodal',
            name='group_user',
        ),
        migrations.CreateModel(
            name='ScriptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('script', models.CharField(blank=True, max_length=200, null=True, verbose_name='Script')),
                ('lot_size', models.IntegerField(default=0, verbose_name='Lot Size')),
                ('qty_max', models.IntegerField(default=0, verbose_name='Qty Max')),
                ('lot_max', models.IntegerField(default=0, verbose_name='Lot Max')),
                ('breakup_qty', models.IntegerField(default=0, verbose_name='Breakup Qty')),
                ('breakup_lot', models.IntegerField(default=0, verbose_name='Break Lot')),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to='App.groupsettingsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
